import { useState, useEffect, useRef } from 'react';
import axios from 'axios';
import toast from 'react-hot-toast';
import { BookOpen, RefreshCw, ChevronRight, Zap, CheckCircle, XCircle, Info, Lock, Star, Clock, BarChart2, Layers } from 'lucide-react';
import XPReward from '../components/XPReward';
import { useAuth } from '../context/AuthContext';

const TIER_LABELS = { beginner:'🟢 Beginner', elementary:'🟡 Elementary', intermediate:'🟠 Intermediate', upper_intermediate:'🔴 Upper Intermediate', advanced:'🔥 Advanced', expert:'💎 Expert' };

function BookLibrary({ library, onSelectBook, onSwitchToArticle }) {
  const [activeTab, setActiveTab] = useState('books');
  const tiers = ['beginner','elementary','intermediate','upper_intermediate','advanced','expert'];

  return (
    <div className="max-w-5xl mx-auto animate-slide-up">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 bg-gradient-to-br from-green-600 to-emerald-500 rounded-xl flex items-center justify-center"><BookOpen size={22} className="text-white" /></div>
        <div>
          <h1 className="text-2xl font-display font-bold text-white">Reading Centre</h1>
          <p className="text-slate-400 text-sm">Read real books or AI articles — questions generated by AI</p>
        </div>
      </div>

      <div className="flex gap-2 mb-6">
        <button onClick={() => setActiveTab('books')} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium transition-all ${activeTab==='books'?'bg-green-500/20 border border-green-500/30 text-green-400':'bg-white/5 text-slate-400 hover:bg-white/10'}`}>
          <BookOpen size={16} /> 📚 Book Library
        </button>
        <button onClick={onSwitchToArticle} className={`flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium transition-all bg-white/5 text-slate-400 hover:bg-white/10`}>
          <Layers size={16} /> 📰 AI Articles
        </button>
      </div>

      <div className="space-y-6">
        {tiers.map(tier => {
          const section = library[tier];
          if (!section) return null;
          return (
            <div key={tier}>
              <div className="flex items-center gap-3 mb-3">
                <h2 className="text-base font-display font-bold text-white">{TIER_LABELS[tier]}</h2>
                {!section.unlocked && <span className="text-xs text-slate-500 bg-dark-600 border border-white/10 rounded-full px-2 py-0.5">Unlock at Level {section.requiredLevel}</span>}
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                {section.books.map(book => (
                  <button key={book.id} onClick={() => section.unlocked ? onSelectBook(book) : toast.error(`Reach Level ${section.requiredLevel} to unlock!`)}
                    className={`glass-card p-4 text-left transition-all duration-200 relative overflow-hidden group ${section.unlocked?'hover:scale-[1.02] hover:border-green-500/20 cursor-pointer':'opacity-50 cursor-not-allowed'}`}>
                    {!section.unlocked && <div className="absolute top-2 right-2"><Lock size={14} className="text-slate-500" /></div>}
                    <div className="text-3xl mb-3">{book.emoji}</div>
                    <h3 className="font-display font-bold text-white text-sm mb-1 leading-tight">{book.title}</h3>
                    <p className="text-xs text-slate-500 mb-2">by {book.author}</p>
                    <p className="text-xs text-slate-400 leading-relaxed line-clamp-2">{book.description}</p>
                    <div className="mt-3 flex items-center justify-between">
                      <span className="text-xs bg-dark-600 border border-white/5 rounded-full px-2 py-0.5 text-slate-400">{book.genre}</span>
                      {section.unlocked && <span className="text-xs text-green-400 flex items-center gap-1 group-hover:gap-2 transition-all">Read <ChevronRight size={10} /></span>}
                    </div>
                  </button>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function ArticleMode({ genres, onBack }) {
  const [selectedGenre, setSelectedGenre] = useState('General Knowledge');
  const [exercise, setExercise] = useState(null);
  const [loading, setLoading] = useState(false);
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [result, setResult] = useState(null);
  const [reward, setReward] = useState(null);
  const [showExplanation, setShowExplanation] = useState({});
  const [startTime, setStartTime] = useState(null);
  const [wpm, setWpm] = useState(0);
  const readStartRef = useRef(null);
  const { fetchProfile } = useAuth();

  const generate = async () => {
    setLoading(true); setAnswers({}); setSubmitted(false); setResult(null); setReward(null); setShowExplanation({}); setExercise(null);
    try {
      const { data } = await axios.post('/api/reading/generate', { genre: selectedGenre });
      setExercise(data); setStartTime(Date.now()); readStartRef.current = Date.now();
    } catch { toast.error('Failed to generate. Try again!'); }
    finally { setLoading(false); }
  };

  const handleStartQuiz = () => {
    if (readStartRef.current) {
      const elapsed = (Date.now() - readStartRef.current) / 1000 / 60;
      const words = exercise.passage?.split(/\s+/).length || 0;
      setWpm(Math.round(words / elapsed));
    }
  };

  const handleSubmit = async () => {
    const unanswered = exercise.questions.filter((_,i) => answers[i]===undefined);
    if (unanswered.length) return toast.error('Answer all questions!');
    setSubmitted(true);
    try {
      const ansArr = exercise.questions.map((_,i) => answers[i]);
      const timeSpent = startTime ? Math.floor((Date.now()-startTime)/1000) : 0;
      const { data } = await axios.post('/api/reading/submit', { answers: ansArr, questions: exercise.questions, topic: exercise.title, timeSpent, wpm });
      setResult(data); setReward({ xp: data.xpEarned, coins: data.coinsEarned, score: data.score });
      await fetchProfile();
    } catch { toast.error('Submission failed'); }
  };

  if (!exercise) return (
    <div className="max-w-3xl mx-auto animate-slide-up">
      <div className="flex items-center gap-3 mb-6">
        <button onClick={onBack} className="btn-ghost text-sm py-2 px-3 flex items-center gap-1"><ChevronRight size={14} className="rotate-180" /> Book Library</button>
        <h2 className="text-xl font-display font-bold text-white">AI Article Mode</h2>
      </div>
      <div className="glass-card p-6">
        <h3 className="font-semibold text-white mb-4">Choose a Genre</h3>
        <div className="flex flex-wrap gap-2 mb-6">
          {genres.map(g => <button key={g} onClick={() => setSelectedGenre(g)} className={`text-xs px-3 py-1.5 rounded-full border transition-all ${selectedGenre===g?'bg-green-500/20 border-green-500/40 text-green-400':'border-white/10 text-slate-400 hover:border-white/20'}`}>{g}</button>)}
        </div>
        <button onClick={generate} disabled={loading} className="btn-primary w-full flex items-center justify-center gap-2">
          {loading?<><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"/>Generating...</>:<><BookOpen size={16}/>Generate Article</>}
        </button>
      </div>
    </div>
  );

  return <ReadingExercise exercise={exercise} answers={answers} setAnswers={setAnswers} submitted={submitted} result={result} reward={reward} showExplanation={showExplanation} setShowExplanation={setShowExplanation} wpm={wpm} onStartQuiz={handleStartQuiz} onSubmit={handleSubmit} onReset={() => {setExercise(null);setResult(null);setReward(null);}} title={exercise.title} isBook={false} onBack={onBack} setReward={setReward} />;
}

function ReadingExercise({ exercise, answers, setAnswers, submitted, result, reward, showExplanation, setShowExplanation, wpm, onStartQuiz, onSubmit, onReset, title, isBook, onBack, setReward }) {
  const [quizMode, setQuizMode] = useState(false);

  return (
    <div className="max-w-3xl mx-auto animate-slide-up">
      {reward && <XPReward {...reward} onClose={() => setReward(null)} />}
      <div className="flex items-center gap-3 mb-6">
        <button onClick={onBack} className="btn-ghost text-sm py-2 px-3 flex items-center gap-1"><ChevronRight size={14} className="rotate-180" /> {isBook?'Library':'Articles'}</button>
        <h2 className="text-xl font-display font-bold text-white truncate">{title || exercise.title}</h2>
      </div>

      {!quizMode ? (
        <div className="space-y-4">
          <div className="glass-card p-6 border-green-500/20">
            <div className="flex items-center justify-between mb-4">
              <div>
                <h3 className="font-display font-bold text-white text-lg">{exercise.title || title}</h3>
                {exercise.chapterHint && <p className="text-xs text-slate-500 mt-1">{exercise.chapterHint}</p>}
              </div>
              {exercise.difficulty && <span className="text-xs bg-green-500/10 text-green-400 border border-green-500/20 rounded-full px-3 py-1 capitalize">{exercise.difficulty?.replace('_',' ')}</span>}
            </div>
            <p className="text-slate-300 leading-[1.9] text-sm whitespace-pre-wrap">{exercise.passage}</p>
            {exercise.summary && <div className="mt-4 p-3 bg-dark-600/50 rounded-xl border border-white/5"><p className="text-xs text-slate-500 mb-1">Summary:</p><p className="text-xs text-slate-400 italic">{exercise.summary}</p></div>}

            {exercise.vocabulary?.length > 0 && (
              <div className="mt-4">
                <p className="text-xs text-slate-500 mb-2">📚 Key Vocabulary:</p>
                <div className="flex flex-wrap gap-2">
                  {exercise.vocabulary.map((v,i) => (
                    <div key={i} title={v.definition} className="text-xs bg-dark-600 border border-white/10 rounded-lg px-2 py-1 text-slate-300 cursor-help">
                      <span className="font-medium">{v.word}</span>
                      {v.level && <span className={`ml-1 ${v.level==='beginner'?'text-green-400':v.level==='intermediate'?'text-yellow-400':'text-red-400'}`}>•</span>}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="glass-card p-4 flex items-center justify-between">
            <div className="text-xs text-slate-400">
              <span>📖 {exercise.passage?.split(/\s+/).length || 0} words</span>
              {wpm > 0 && <span className="ml-3">⚡ {wpm} WPM</span>}
            </div>
            <button onClick={() => { onStartQuiz(); setQuizMode(true); }} className="btn-primary flex items-center gap-2 text-sm py-2.5">
              I'm Ready — Test Me <ChevronRight size={16} />
            </button>
          </div>
        </div>
      ) : (
        <div className="space-y-4">
          {wpm > 0 && (
            <div className="glass-card p-3 flex items-center gap-3">
              <BarChart2 size={16} className="text-green-400" />
              <span className="text-sm text-slate-300">Reading speed: <span className="text-green-400 font-bold">{wpm} WPM</span></span>
              {wpm >= 200 && <span className="text-xs bg-green-500/20 text-green-400 border border-green-500/20 rounded-full px-2 py-0.5">🚀 Fast Reader!</span>}
            </div>
          )}

          {exercise.questions.map((q,qi) => (
            <div key={q.id} className="glass-card p-5">
              <p className="font-medium text-white mb-3 text-sm">{qi+1}. {q.question}</p>
              <div className="space-y-2">
                {q.options.map((opt,oi) => {
                  const isSelected = answers[qi]===oi;
                  const isCorrect = submitted && oi===q.correct;
                  const isWrong = submitted && isSelected && oi!==q.correct;
                  return (
                    <button key={oi} onClick={() => !submitted && setAnswers(p=>({...p,[qi]:oi}))}
                      className={`w-full text-left px-4 py-3 rounded-xl border text-sm transition-all flex items-center gap-3 ${isCorrect?'border-green-500/50 bg-green-500/10 text-green-400':isWrong?'border-red-500/50 bg-red-500/10 text-red-400':isSelected?'border-green-500/50 bg-green-500/10 text-green-300':'border-white/10 text-slate-300 hover:border-white/20 hover:bg-white/5'} ${submitted?'cursor-default':'cursor-pointer'}`}>
                      <span className="w-5 h-5 rounded-full border border-current flex items-center justify-center text-xs shrink-0">{String.fromCharCode(65+oi)}</span>
                      <span className="flex-1">{opt}</span>
                      {isCorrect && <CheckCircle size={16} />}
                      {isWrong && <XCircle size={16} />}
                    </button>
                  );
                })}
              </div>
              {submitted && q.explanation && (
                <div className="mt-2">
                  <button onClick={() => setShowExplanation(p=>({...p,[qi]:!p[qi]}))} className="text-xs flex items-center gap-1 text-primary-400 hover:text-primary-300">
                    <Info size={12} /> {showExplanation[qi]?'Hide':'Show'} Explanation
                  </button>
                  {showExplanation[qi] && <p className="text-xs text-slate-400 mt-2 p-3 bg-dark-600/50 rounded-lg">{q.explanation}</p>}
                </div>
              )}
            </div>
          ))}

          {!submitted ? (
            <button onClick={onSubmit} className="btn-primary w-full flex items-center justify-center gap-2"><ChevronRight size={16}/> Submit Answers</button>
          ) : result && (
            <div className="glass-card p-6 bg-gradient-to-br from-green-500/10 to-emerald-500/10 border-green-500/20">
              <div className="flex items-center justify-between mb-3">
                <h3 className="font-display font-bold text-white">Result</h3>
                <span className={`text-3xl font-display font-bold ${result.score>=80?'text-green-400':result.score>=60?'text-yellow-400':'text-red-400'}`}>{result.score}%</span>
              </div>
              <p className="text-slate-300 mb-3">{result.correct} / {result.total} correct</p>
              {wpm > 0 && <p className="text-xs text-slate-400 mb-3">Reading speed: {wpm} WPM {wpm>=200?'🚀':wpm>=150?'⚡':''}</p>}
              <div className="flex gap-2 mb-4"><span className="xp-badge"><Zap size={12}/>+{result.xpEarned} XP</span></div>
              <button onClick={onReset} className="btn-ghost w-full flex items-center justify-center gap-2 text-sm"><RefreshCw size={14}/> Read Another</button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function Reading() {
  const [phase, setPhase] = useState('library');
  const [library, setLibrary] = useState({});
  const [genres, setGenres] = useState([]);
  const [selectedBook, setSelectedBook] = useState(null);
  const [bookExercise, setBookExercise] = useState(null);
  const [bookLoading, setBookLoading] = useState(false);
  const [answers, setAnswers] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [result, setResult] = useState(null);
  const [reward, setReward] = useState(null);
  const [showExplanation, setShowExplanation] = useState({});
  const [wpm, setWpm] = useState(0);
  const readStartRef = useRef(null);
  const { fetchProfile } = useAuth();

  useEffect(() => {
    Promise.all([axios.get('/api/reading/books'), axios.get('/api/reading/genres')])
      .then(([b, g]) => { setLibrary(b.data.library || {}); setGenres(g.data.genres || []); })
      .catch(() => toast.error('Failed to load reading content'));
  }, []);

  const handleSelectBook = async (book) => {
    setSelectedBook(book); setBookLoading(true); setAnswers({}); setSubmitted(false); setResult(null); setReward(null); setShowExplanation({});
    try {
      const { data } = await axios.post('/api/reading/book-passage', { bookId: book.id });
      setBookExercise(data); readStartRef.current = Date.now(); setPhase('book-read');
    } catch { toast.error('Failed to load book passage. Try again!'); setSelectedBook(null); }
    finally { setBookLoading(false); }
  };

  const handleBookSubmit = async () => {
    const unanswered = bookExercise.questions.filter((_,i) => answers[i]===undefined);
    if (unanswered.length) return toast.error('Answer all questions!');
    setSubmitted(true);
    try {
      const ansArr = bookExercise.questions.map((_,i) => answers[i]);
      const timeSpent = readStartRef.current ? Math.floor((Date.now()-readStartRef.current)/1000) : 0;
      const { data } = await axios.post('/api/reading/submit', { answers: ansArr, questions: bookExercise.questions, topic: selectedBook.title, timeSpent, wpm });
      setResult(data); setReward({ xp: data.xpEarned, coins: data.coinsEarned, score: data.score });
      await fetchProfile();
    } catch { toast.error('Submission failed'); }
  };

  if (bookLoading) return (
    <div className="flex items-center justify-center h-64">
      <div className="flex flex-col items-center gap-4">
        <div className="w-10 h-10 border-2 border-green-500 border-t-transparent rounded-full animate-spin" />
        <p className="text-slate-400 text-sm">Loading book passage from library...</p>
      </div>
    </div>
  );

  if (phase === 'book-read' && bookExercise) return (
    <ReadingExercise
      exercise={bookExercise} answers={answers} setAnswers={setAnswers}
      submitted={submitted} result={result} reward={reward}
      showExplanation={showExplanation} setShowExplanation={setShowExplanation}
      wpm={wpm} onStartQuiz={() => { if(readStartRef.current){const e=(Date.now()-readStartRef.current)/1000/60;const w=bookExercise.passage?.split(/\s+/).length||0;setWpm(Math.round(w/e));} }}
      onSubmit={handleBookSubmit} onReset={() => { setPhase('library'); setBookExercise(null); setSelectedBook(null); setResult(null); setReward(null); }}
      title={selectedBook?.title} isBook={true} onBack={() => setPhase('library')} setReward={setReward}
    />
  );

  if (phase === 'article') return <ArticleMode genres={genres} onBack={() => setPhase('library')} />;

  return <BookLibrary library={library} onSelectBook={handleSelectBook} onSwitchToArticle={() => setPhase('article')} />;
}
